'use babel';

export const UPDATE_TRACK_DETAILS = 'UPDATE_TRACK_DETAILS';
export const UPDATE_PLAYER_DETAILS = 'UPDATE_PLAYER_DETAILS';
export const UPDATE_DISPLAY_SETTINGS = 'UPDATE_DISPLAY_SETTINGS';
export const UPDATE_SPOTIFY_IS_OPEN = 'UPDATE_SPOTIFY_IS_OPEN';
